---
title: "First Knit"
author: "Luz Vargas"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct punctuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare English class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer
For my Freshmen and Sophomore year of High School I attended Palmdale High. Since I got pregnant during my Sophmore year I ended up falling behind and missing a lot of credits so I had to finish my Junior and Senior year at R.Rex Parris High School, which actually helped me graduate 2 months earlier then planned. English classes usually involve writing a lot of essays and math involves more problem solving. I used to think math was easier than English because math felt like it came with instructions so it was easier to just follow along  and go back if I missed a step. As I take higher math classes, I now realize that English is easier than math for me because it is all just one language. Although I got an A in both Math 102 and English 102, I still feel like I do the best in English. I guess this will be the ultimate test.
  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I own an HP Chromebook x360 laptop, it is way faster then the last computer I owned which was a Lenavo. From a scale of 1 to 10, I am honestly close to being a dummy when it comes to computers. I would rate myself a 4.5 out of 10 because I know do know the basics to a computer but that's about it. Since my boyfriend and my son love playing video games, I actually had to purchase fast speed internet so that none of our networks lag ever.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  I prefer for my classmates and my instructor to call me by my first name.
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  I want to make sure I am a dermatologist by the age of 32. I think the subject that I am most interested in taking is Anatomy because in Dermatology they perform lots of surgeries so if I become an expert at knowing the structure of our bodies my job will be easier. First I want to get my Associate's Degree in nursing and then further my education online to become a Nurse Practitioner and then specialize in Dermatology.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   I have never gone to any foreign countries, but in the future I might go to Greece. I've always wanted to visit to Greece to see their beautiful blue beaches and their ancient buildings. I have never been in the military but if I had to choose a branch to get drafted for I would choose the air force since they have the easiest training out of all the branches.
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
  I'm taking Math 115 only since I do not Math 116 to get into the nursing program.  I must get an A in stats to get priority entrance into the nursing program. If I do not get an A, I will more than likely be wait listed for the nursing program which I hear is very long wait. My plan is to take this class very serious and re-watch all the class videos to make sure I follow along good. I have even dropped my Biology class so that I can just focus on this class.
 






  




